### PR TITLE
Pull request for rounding

### PR DESCRIPTION
**Pull request by Morphan1**
Please excuse the merges o.O

### CODE REVIEW

**Comment by mcmonkey4eva** [comment]
Could you like... remake this, without having 5 separate merges.

**Comment by Morphan1** [comment]
Whyyy? It's not like they'll be right next to each other

**Comment by mcmonkey4eva** [comment]
@.@

**Comment by Morphan1** [comment]
Sooo?

**Comment by mcmonkey4eva** [comment]
Fiiiixx iittttttt

**Pull request closed without merging**
