### PR TITLE
Cleaning up some tLC logic

### PR DESCRIPTION
**Pull request by Talamar1**

### CODE REVIEW

**Comment by mcmonkey4eva** [comment]
PR made to the wrong repo?

**Comment by Talamar1** [comment]
Nope, had to update my local with a master pull to get it uptodate before it would let me push.

**Comment by mcmonkey4eva** [comment]
Pretty sure this is the wrong repo.

**Comment by Talamar1** [comment]
isn't:
src/main/java/net/aufdemrand/denizencore/utilities/text/StringHolder.java
part of this repo?

**Pull request closed without merging**
